item/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 21:10:14 2021

@author: Vashti
"""

from . import views
from django.urls import path

app_name = 'item'

urlpatterns = [
    path("item/<int:pk>/", views.ItemView.as_view(), name="view"),
    path("item/create/", views.ItemCreateView.as_view(), name="create"),
    path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name='edit'),
    path("item/<int:pk>/delete/", views.ItemDeleteView.as_view(), name='delete'),
    path("profile/listings", views.UserItemsView.as_view(), name='user_listings'),
    path("profile/sold", views.UserSoldView.as_view(), name='user_sold'),
    ]

kijiji_like/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('', include('item.urls', namespace="item")),
    path('', include('like.urls', namespace="like")),
    path('', include('comment.urls', namespace="comment")),
    path('', include('order.urls', namespace="order")),
    path('', include('search.urls', namespace='search')),
]

search/urls.py
from . import views
from django.urls import path

app_name = 'search'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("search/", views.SearchView.as_view(), name="search"),
    ]

search/models.py
from django.db import models


# Create your models here.

search/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from item.models import Category, Item
from django.db.models import Count
from django.http import Http404

# Create your views here.
'''
This is the index view. It is the main page of the website and
it will allow any users to view all items.
''' 
class IndexView(generic.ListView):
    template_name = 'search/index.html'
    paginate_by = 10
    context_object_name = 'items'
    
    def get_queryset(self):
        queryset = Item.objects.filter(is_bought=False).order_by("-creation_date")
        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["user"] = self.request.user
        
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                context["base_template_name"] = "base_superuser.html"
            else:
                context["base_template_name"] = "base_user.html"
        else:
            context["base_template_name"] = "base.html"
            
        return context

   
'''
This is the search view. It will show items based on a GET request
values.
''' 
class SearchView(generic.ListView):
    template_name = 'search/search.html'
    paginate_by = 10
    context_object_name = 'items'
    
    def get_queryset(self):
        try:
            search = self.request.GET
            queryset = Item.objects.filter(item_name__icontains = search.get("search_text"), is_bought=False)
            
            #Get specific items from category if category is specified
            if search.get("category") is not None:
                category = Category.objects.get(category_name = search.get("category"))
                queryset = queryset.filter(category = category)
            
            #Sort items if a sort option is elected
            sort = search.get("sort") 
            if sort is not None:
                if sort == "popular":
                    queryset = queryset.annotate(num_likes=Count('like')).order_by('-num_likes')
                elif sort == "newest":
                    queryset = queryset.order_by("-creation_date")
                elif sort == "oldest":
                    queryset = queryset.order_by("creation_date")
            
            return queryset
        except ValueError:
            raise Http404
            
    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        context["user"] = self.request.user
        
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                context["base_template_name"] = "base_superuser.html"
            else:
                context["base_template_name"] = "base_user.html"
        else:
            context["base_template_name"] = "base.html"
        
        return context

search/templates/search/index.html
{% extends base_template_name %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'search/css/index_style.css' %}">
{% endblock extra_head %}

{% block content %}
<section id="search_bar">
<form method="GET" action="{% url 'search:search' %}">
    <input type='text' maxlength=100 
        placeholder="Search Item" name="search_text">
        
        <div id='categories'>       
        <h3 id="category_header">Categories: </h3>   
            {% for category in categories %}
            <p>
                <input type="radio" name="category" 
                    id="category{{forloop.counter}}" 
                    value="{{category.category_name}}">
                <label for="category{{forloop.counter}}">{{category.category_name}}</br>
               </p>
            {% endfor %}
        </div>
        
        <div id='sort'>
        <h3 id="sort_header">Sort by:</h3>
            <p>
                <input type='radio' radio name="sort" id="popular" value="popular">
                <label for='popular'>Most popular</label>
            </p>
            <p>
                <input type='radio' radio name="sort"' id="newest" value="newest" checked>
                <label for='newest'>Date added (newest)</label>
            </p>
            <p>
                <input type='radio' radio name="sort"' id="oldest" value="oldest">
                <label for='oldest'>Date added (oldest)</label> 
            </p>
        </div>
    </form>
</section>

<h1 id="recent_header">Recent Items Posted</h1>
<section id="item_list">
{% for item in items %}
    <a href="{% url 'item:view' item.item_id %}">
        <div class='items'>
            <h1>{{item.item_name}}</h1>
            <p>Price: <u><b>${{item.price}}</b></u></p>
            <div>
                <img src="{% static item.image.url %}">
            </div>   
        </div>
    </a>
{% empty %}
<p> a wasteland...</p>
{% endfor %}
</section>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}

search/templates/search/search.html
{% extends base_template_name %}
{% load static %}

{% block title %} Home {% endblock title %}

{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'search/css/index_style.css' %}">
{% endblock extra_head %}

 {% block extra_options %}
 <li id="post_option"><a href="{% url 'item:create' %}">Post New Item</a></li>
 {% endblock extra_options %}


{% block content %}
<section id="search_bar">
<form method="GET" action="{% url 'search:search' %}">
    <input type='text' maxlength=100 
        placeholder="Search Item" name="search_text">
        
        <div id='categories'>       
        <h3 id="category_header">Categories: </h3>   
            {% for category in categories %}
            <p>
                <input type="radio" name="category" 
                    id="category{{forloop.counter}}" 
                    value="{{category.category_name}}">
                <label for="category{{forloop.counter}}">{{category.category_name}}</br>
               </p>
            {% endfor %}
        </div>
        
        <div id='sort'>
        <h3 id="sort_header">Sort by:</h3>
            <p>
                <input type='radio' radio name="sort" id="popular" value="popular">
                <label for='popular'>Most popular</label>
            </p>
            <p>
                <input type='radio' radio name="sort"' id="newest" value="newest" checked>
                <label for='newest'>Date added (newest)</label>
            </p>
            <p>
                <input type='radio' radio name="sort"' id="oldest" value="oldest">
                <label for='oldest'>Date added (oldest)</label> 
            </p>
        </div>
    </form>
</section>

<h1>Your search returned <b>{{items | length}}</b> results.</h1>
<section id="item_list">
{% for item in items %}
    <a href="{% url 'item:view' item.item_id %}">
        <div class='items'>
            <h1>{{item.item_name}}</h1>
            <p>Price: <u><b>${{item.price}}</b></u></p>
            <div>
                <img src="{% static item.image.url %}">
            </div>   
        </div>
    </a>
{% empty %}
<p> a wasteland...</p>
{% endfor %}
</section>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock content %}