comment/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'comment'


urlpatterns = [
    path("item/<int:pk>/comment", views.CreateCommentView.as_view(), name='comment'),
    ]

item/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 21:10:14 2021

@author: Vashti
"""

from . import views
from django.urls import path

app_name = 'item'

urlpatterns = [
    path("item/<int:pk>/", views.ItemView.as_view(), name="view"),
    path("item/create/", views.ItemCreateView.as_view(), name="create"),
    path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name='edit'),
    path("item/<int:pk>/delete/", views.ItemDeleteView.as_view(), name='delete'),
    path("profile/listings", views.UserItemsView.as_view(), name='user_listings'),
    path("profile/sold", views.UserSoldView.as_view(), name='user_sold'),
    ]

kijiji_like/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('', include('item.urls', namespace="item")),
    path('', include('like.urls', namespace="like")),
    path('', include('comment.urls', namespace="comment")),
    path('', include('order.urls', namespace="order")),
    path('', include('search.urls', namespace='search')),
]

like/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'like'


urlpatterns = [
    path("item/<int:pk>/like", views.item_liked, name='like'),
    ]

order/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, include
from . import views

app_name = 'order'

urlpatterns=[
    path("item/<int:pk>/buy/", views.buy_item_view, name='buy'),
    path("profile/orders", views.UserOrdersView.as_view(), name="user_orders")
    ]

item/models.py
'''
This is the model for item app.

@author Vashti
'''

from django.db import models
from user.models import User
import time

#Helper methods
'''
This method is used to create a unique name for the image.
---
Return:
    filename -> item/<date+time>.<file's extension>
'''   
def upload_to(instance, filename):
        ext = filename.split('.')[-1] #Go to the last index -> extension
        return 'items/%f.%s' % (time.time(), ext)
#Models
'''
This class represents the Category table.
'''
class Category(models.Model):
    category_id = models.AutoField(primary_key = True)
    category_name = models.CharField(max_length = 60)
    
    '''
    This method is used to return the name of the category
    when referring to the object.
    ---
    Returns:
        category_name = category id
    '''   
    def __str__(self):
        return self.category_name
    
    '''
    This sets the plural of "Category" to "Categories"
    '''
    class Meta:
        verbose_name_plural = "Categories"
    
'''
This class represents the Item table.
'''
class Item(models.Model):
    item_id = models.AutoField(primary_key = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)
    price = models.DecimalField(decimal_places = 2, max_digits = 10)
    item_name = models.CharField(max_length = 25)
    description = models.TextField()
    category = models.ForeignKey(Category, on_delete= models.CASCADE)
    image = models.ImageField(upload_to=upload_to)
    is_bought = models.BooleanField(default = False)
    creation_date = models.DateTimeField(auto_now=True)
    
    '''
    This method is used to return the name of the item
    when referring to the object.
    ---
    Returns:
        item_name = Item name
    '''
    def __str__(self):
        return self.item_name
    
    def is_allowed_to_edit(self, user):
        if user.is_authenticated:
            return self.owner.username == user.username or user.is_superuser
        else:
            return False
     

like/models.py
from django.db import models
from item.models import Item
from user.models import User

# Create your models here.

'''
This is the Like Model. It keeps track of what users liked what item.
'''
class Like(models.Model):
    like_id = models.AutoField(primary_key = True)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE)
    
    def __str__(self):
        return "{}:{}".format(self.item.item_id, self.user.username)

item/forms.py
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 21:14:49 2021

@author: Vashti
"""

from .models import Item
from django import forms

#Forms
'''
This is the form for creating a new item
'''
class ItemCreationForm(forms.ModelForm):
    item_name = forms.CharField(min_length = 4)
    price = forms.DecimalField(decimal_places = 2, max_digits = 10)
    
    class Meta:
        model = Item
        fields = ("item_name", "price", "description", "category", "image")
    
    '''
    This checks if the price is not 0 or less. It will throw a
    ValidationError if invalid price is found
    ---
    Returns:
        price
    '''
    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price <= 0:
            raise forms.ValidationError("Price cannot be 0 or less.")
        return price
    
    '''
    This method saves the item in the database.
    ---
    Returns:
        item
    '''
    def save(self, commit=True):
        item = super().save(commit=False)
        item.is_bought = False
        if commit:
            item.save()
        return item

'''
This class is a form for editing items.
'''
class ItemEditForm(forms.ModelForm):
    item_name = forms.CharField(min_length = 4)
    price = forms.DecimalField(decimal_places = 2, max_digits = 10)
    image = forms.ImageField(widget=forms.FileInput)
    
    class Meta:
        model = Item
        fields = ("item_name", "price", "description", "category", "image")
    
    '''
    This checks if the price is not 0 or less. It will throw a
    ValidationError if invalid price is found
    ---
    Returns:
        price
    '''
    def clean_price(self):
        price = self.cleaned_data.get("price")
        if price <= 0:
            raise forms.ValidationError("Price cannot be 0 or less.")
        return price

    '''
    This method saves the item in the database.
    ---
    Returns:
        item
    '''
    def save(self, commit=True):
        item = super().save(commit=False)
        item.item_name = self.cleaned_data.get("item_name")
        item.price = self.cleaned_data.get("price")
        item.description = self.cleaned_data.get("description")
        item.category = self.cleaned_data.get("category")
        item.image = self.cleaned_data.get("image")
        
        if commit:
            item.save()
        return item
    

item/views.py
from django.shortcuts import get_object_or_404
from .forms import ItemCreationForm, ItemEditForm
from .models import Item
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse

# Create your views here.
'''
This is the create item view. It allows the user to post an
item for sale. User must also be logged in to access this
page.
'''
class ItemCreateView(LoginRequiredMixin, generic.CreateView):
    login_url = "/login/"
    model = Item
    form_class = ItemCreationForm
    template_name = "items/create.html"
    
    #Set url when item creation is successful.
    def get_success_url(self):
        return reverse("item:view", kwargs ={"pk": self.pk})
    
    '''
    This method is called when user submits form and is valid. 
    It will save the item and associate the user as the owner
    '''
    def form_valid(self, form):
        item = form.save(commit=False)
        item.owner = self.request.user
        item.save()
        self.pk = item.pk
        return super(ItemCreateView, self).form_valid(form)
    
    def get_context_data(self, **kwargs):
        context = super(ItemCreateView, self).get_context_data(**kwargs)
        context["user"] = self.request.user
        if self.request.user.is_superuser:
            context["base_template_name"] = "base_superuser.html"
        else:
            context["base_template_name"] = "base_user.html"    
        
        return context
    

'''
This is the create item view. It allows anyone to view an
item for sale. Non-logged in/specific users will not be able to get
full functionality like commenting, liking, editing, deleting the item.
'''
class ItemView(generic.DetailView):
    model = Item
    template_name = "items/view.html"
    
    #Set the context variable
    def get_context_data(self, **kwargs):
        context = super(ItemView, self).get_context_data(**kwargs)
        item = get_object_or_404(Item, item_id = self.kwargs["pk"], is_bought = False)
        context["item"] = item
        if self.request.user.is_authenticated:
            context['user_liked'] = len(item.like_set
                                    .filter(item=item, 
                                            user=self.request.user)) != 0
            
        context["comments"] = item.comment_set.all().order_by("-comment_date")
        if self.request.user.is_authenticated:
            if self.request.user.is_superuser:
                context["base_template_name"] = "base_superuser.html"
            else:
                context["base_template_name"] = "base_user.html"
        else:
            context["base_template_name"] = "base.html"
        return context

'''
This is the edit item view. It will allow the item owner to edit
the item's information. Only specific users will be able the item.
'''
class ItemEditView(generic.UpdateView):
    model = Item
    template_name = "items/edit.html"
    form_class = ItemEditForm
    
    #Set the context variable
    def get_context_data(self, **kwargs):
        context = super(ItemEditView, self).get_context_data(**kwargs)
        item = get_object_or_404(Item, item_id = self.kwargs["pk"], is_bought = False)
        
        #Verify if the user is allowed to edit
        if item.is_allowed_to_edit(self.request.user) == False: 
            context["user_not_allowed"] = "You are not allowed to view this page."
        
        if self.request.user.is_authenticated:     
            if self.request.user.is_superuser:
                context["base_template_name"] = "base_superuser.html"
            else:
                context["base_template_name"] = "base_user.html"
        else:
            context["base_template_name"] = "base.html"
            
        return context
    
    #Set successful url to be the item's view page
    def get_success_url(self):
        return reverse("item:view", kwargs={"pk": self.pk})
    
    
    def form_valid(self, form):
        item = form.save()
        self.pk = item.item_id
        return super(ItemEditView, self).form_valid(form)  


'''
This is the edit item view. It will allow the item owner to
delete their item. Only specific users will be able to view
this page.
'''
class ItemDeleteView(generic.DeleteView):
    model = Item
    template_name = "items/delete.html"
    success_url = "/"
    succuess_message = "Successfully deleted item."
    
    #Set the context variable
    def get_context_data(self, **kwargs):
        context = super(ItemDeleteView, self).get_context_data(**kwargs)
        item = get_object_or_404(Item, item_id = self.kwargs["pk"], is_bought = False)
        
        #Verify if the user is allowed to edit
        if item.is_allowed_to_edit(self.request.user) == False:
            context["user_not_allowed"] = "You are not allowed to view this page."
        context["item"] = item
        
        if self.request.user.is_authenticated:     
            if self.request.user.is_superuser:
                context["base_template_name"] = "base_superuser.html"
            else:
                context["base_template_name"] = "base_user.html"
        else:
            context["base_template_name"] = "base.html"
        return context
  
'''
This is the view for user's items. It will only display items that they
have posted that are not sold out.
'''    
class UserItemsView(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    template_name = 'profile/items.html'
    paginate_by = 10
    context_object_name = 'items'
    
    def get_queryset(self):
        queryset = Item.objects.filter(owner=self.request.user, is_bought=False).order_by("-creation_date")
        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(UserItemsView, self).get_context_data(**kwargs)
        context["user"] = self.request.user
        context["display_not_sold"] = True
        context["title"] = "Currently selling"
        if self.request.user.is_superuser:
            context["base_template_name"] = "base_superuser.html"
        else:
            context["base_template_name"] = "base_user.html"  
            
        return context

'''
This is the view for user's items. It will only display items that they
have posted that are sold out.
'''
class UserSoldView(LoginRequiredMixin, generic.ListView):   
    login_url = '/login/'
    template_name = 'profile/items.html'
    paginate_by = 10
    context_object_name = 'items'
    
    def get_queryset(self):
        queryset = Item.objects.filter(owner=self.request.user, is_bought=True).order_by("-creation_date")
        return queryset
        
    def get_context_data(self, **kwargs):
        context = super(UserSoldView, self).get_context_data(**kwargs)
        context["user"] = self.request.user
        context["display_not_sold"] = False
        context["title"] = "Sold"
        context["sold_view"] = True
        if self.request.user.is_superuser:
            context["base_template_name"] = "base_superuser.html"
        else:
            context["base_template_name"] = "base_user.html"    
        
        return context

item/templates/items/create.html
{% extends base_template_name %}
{% load static %}

{% block title %}Creating Item{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'item/css/create_style.css' %}">
{% endblock extra_head %}
{% block content %}
<h1>Post New Item</h1>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
        <p>  
                {{field.label}}
                {{field}}
                
                {%if field.help_text %}
                    <small style="color: grey;">{{field.help_text}}</small>
                {% endif %}
                
                {% for error in field.errors %}
                    <p style="color: red;">{{error}}</p>
                {% endfor %}
        </p>
    {% endfor %}
    <button type="submit">Post</button>
</form>
{% endblock content %}

item/templates/items/delete.html
{% extends base_template_name %}
{% load static %}

{% block title %}Deleting Item{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'item/css/create_style.css' %}">
{% endblock extra_head %}

{% block content %}

{% if user_not_allowed %}
    <div id='cant_buy_own'><h1>{{user_not_allowed}}</h1></div>
{% else %}
   <form method="post">
   {% csrf_token %}
        <p>Are you sure you want to delete "{{ item }}"?</p>
        <button type="submit">Confirm</button>
    </form>
{% endif %}

{% endblock content %}

item/templates/items/edit.html
{% extends base_template_name %}
{% load static %}

{% block title %}Editing Item{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'item/css/create_style.css' %}">
{% endblock extra_head %}

{% block content %}

{% if user_not_allowed %}
    <div id='cant_buy_own'><h1>{{user_not_allowed}}</h1></div>
{% else %}
    <h1>Edit Item</h1>
    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
            {% for field in form %}
            <p>  
                {{field.label}}
                {{field}}
                    
                {%if field.help_text %}
                    <small style="color: grey;">{{field.help_text}}</small>
                {% endif %}
               
                {% for error in field.errors %}
                      <p style="color: red;">{{error}}</p>
                {% endfor %}
            </p>
             {% endfor %}
        <button type="Submit">Update</button>
    </form>
{% endif %}

{% endblock content %}

item/templates/items/view.html
{% extends base_template_name %}
{% load static %}

{% block title %}Viewing Item{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'item/css/view_style.css' %}">
{% endblock extra_head %}

{% block content %}
<section id='item'>
    <section id='buttons'>
    {% if user.is_authenticated %}
        {% if item.owner.username == user.username or user.is_superuser %}
            <form method="GET" action="{% url 'item:edit' item.item_id %}">
                <button type="submit">Edit item</button>
            </form>
            
            <form action="{% url 'item:delete' item.item_id %}">
                <button type="submit">Delete item</button>
            </form>
        {% endif %}
        
    {% if item.owner.username != user.username %}
            <form action="{% url 'order:buy' item.item_id %}">
                <button type="submit">Buy item</button>
            </form>
    {% endif %}
   {% endif %}
    </section>   
    <p><b>Title:</b> {{item.item_name}}</p>
    <p><b>Price:</b> <span>${{item.price}}</span></p>
    <p><b>Seller:</b> <u>{{item.owner.username}}</u></p>
    <img src="{% static item.image.url %}" alt='none'>
    <p><b>Category:</b> {{item.category.category_name}}</p>
    <p><b>Date Posted:</b> {{item.creation_date}}</p>
    <textarea readonly>{{item.description}}</textarea>  
</section>  

<section id='likes'>
<p><span>{{item.like_set.all | length}}</span>Like{{item.like_set.all | length | pluralize}}</p>
    {% if user.is_authenticated %}
        <form action="{% url 'like:like' item.item_id %}">
            {% if user_liked %}
                <button type="submit" >Unlike</button>
            {% else %}
                <button type="submit">Like</button>
            {% endif %}
        </form>
    {% endif %}
</section>
    


<section id='comment_section'>    
    {% if user.is_authenticated %}
        <form action="{% url 'comment:comment' item.item_id %}">
            <button type="submit">Add Comment</button>
        </form>
    {% endif %}
    <p> {{item.comment_set.all | length}} Comment{{item.like_set.all | length | pluralize}}</p>
    {% for comment in comments %}
        <div class='comments'>
            {% if comment.user.avatar %}
                <img src="{% static comment.user.avatar.url %}">
            {% else %}
                <img src="{% static 'user/image/default-avatar.png' %}">
            {% endif %}
            <div>
                <div id='header'>
                    <h3>{{comment.user}}</h3>
                    <p>{{comment.comment_date}}</p>
                </div>
                <textarea readonly>{{comment.comment_text}}</textarea>
            </div>
        </div>
    {% empty %}
    <p> No comments yet.</p>
    {% endfor %}
</section>
{% endblock content %}