item/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 21:10:14 2021

@author: Vashti
"""

from . import views
from django.urls import path

app_name = 'item'

urlpatterns = [
    path("item/<int:pk>/", views.ItemView.as_view(), name="view"),
    path("item/create/", views.ItemCreateView.as_view(), name="create"),
    path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name='edit'),
    path("item/<int:pk>/delete/", views.ItemDeleteView.as_view(), name='delete'),
    path("profile/listings", views.UserItemsView.as_view(), name='user_listings'),
    path("profile/sold", views.UserSoldView.as_view(), name='user_sold'),
    ]

kijiji_like/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('', include('item.urls', namespace="item")),
    path('', include('like.urls', namespace="like")),
    path('', include('comment.urls', namespace="comment")),
    path('', include('order.urls', namespace="order")),
    path('', include('search.urls', namespace='search')),
]

order/urls.py
# -*- coding: utf-8 -*-

from django.urls import path, include
from . import views

app_name = 'order'

urlpatterns=[
    path("item/<int:pk>/buy/", views.buy_item_view, name='buy'),
    path("profile/orders", views.UserOrdersView.as_view(), name="user_orders")
    ]

user/urls.py
# -*- coding: utf-8 -*-
"""
This module contains the urls of the user app.
Created on Thu Apr 22 10:58:47 2021

@author: Vashti
"""
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("login/", auth_views.LoginView.as_view(template_name="user/login.html"), name='login'),
    path("profile/", views.ProfileView.as_view(), name='profile'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path("profile/edit/", views.EditProfileView.as_view(), name='edit'),
    path("profile/change/", views.change, name='change')
    ]

user/models.py
'''
This module is the model for user app.

@author Vashti
'''
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager

#Helper methods
def upload_to(instance, filename):
    # instance.user -> User model
    # intance.user.user -> User
    return "user/{}/{}".format(instance.username, filename)

#The models
'''
This class is used to handle account manangement. 
It extends to django's BaseUserModel
'''
class UserAccountManager(BaseUserManager):
    '''
    This method is used to create a new User.
    ---
    Parameters:
        username = username
        email = email
        first_name = first name
        last_name = last name
        password = password
        **other fields:
            dob = date of birth
    ---
    Returns:
        User - new User
    '''
    def create_user(self, username, email, first_name, last_name, password, **other_fields):
        if not email:
            raise ValueError("You must provide an email address.")
        
        user = self.model(username = username, email = self.normalize_email(email),
                          first_name = first_name, last_name = last_name, **other_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    '''
    This method is used to create a new superuser.
    ---
    Parameters:
        username = username
        email = email
        first_name = first name
        last_name = last name
        password = password
        **other fields:
            dob = date of birth
    ---
    Returns:
        User - new superuser
    '''
    def create_superuser(self, username, email, first_name, last_name, password, **other_fields):
        #Setting superuser permissions
        other_fields.setdefault('is_staff', True)
        other_fields.setdefault('is_superuser', True)
        
        return self.create_user(username, email, first_name, last_name, password, **other_fields)
'''
This class represents the User table. It creates a 
customer User(instead of django's User model) by extending
AbstractBaseUser and PermissionsMixin.
'''
class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length = 25, unique = True)
    email = models.EmailField(max_length = 60, unique=True)
    first_name = models.CharField(max_length = 20)
    last_name = models.CharField(max_length = 20)
    dob = models.DateField()
    avatar = models.ImageField(blank = True, null = True, upload_to=upload_to)
    balance = models.PositiveIntegerField(default = 1000)
    bio = models.CharField(max_length = 250, blank = True, null = True)
    
    #Setting permissions
    is_staff = models.BooleanField(default = False)
    is_superuser = models.BooleanField(default = False)
    is_active = models.BooleanField(default = True)
    
    #Requirements for a KujujuUser
    USERNAME_FIELD = 'username'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', "dob"];
    
    #Obtain field values
    objects = UserAccountManager()
    
    '''
    This method returns the full name of the User. It overrides
    the django's User model get_full_name()
    ---
    Returns:
        User's first name and last name
    '''
    def get_full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    '''
    This method returns the full name of the User. It overrides
    the django's User model get_full_name()
    ---
    Returns:
        User's first name
    '''
    def get_short_name(self):
        return self.first_name
    
    '''
    This method returns the username of a User object.
    ----
    Returns:
        username - User's username
    '''
    def __str__(self):
        return self.username
    

user/forms.py
# -*- coding: utf-8 -*-
"""
Created on Thu Apr 22 11:54:17 2021

@author: Vashti
"""
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
import datetime

'''
This class is used to manage and create user register form.
'''
class RegisterForm(UserCreationForm):
    username = forms.CharField(min_length = 4, max_length = 25, help_text ="Must be unique, at least 4 characters, and " +
                               "no more than 25 characters.")
    email = forms.EmailField(max_length=60, label = "Email", widget = forms.EmailInput)
    dob = forms.DateField(label = "Date of birth", widget=forms.DateInput(format=('%Y-%m-%d'), 
                                                        attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                        'type': 'date'}))
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "dob", "password1", "password2")

    '''
    This function creates the form field values. It will create a new user
    and put it in the database.
    ---
    Returns:
        user
    '''
    def save(self, commit = True):
        user = super().save(commit=False)
        if commit:
            user.save()
        return user

    '''
    This function is used to validate the date of birth value
    from the form. It will throw a ValidationError if it is invalid.
    ---
    Returns
        dob
    '''
    def clean_dob(self):
        dob = self.cleaned_data.get("dob")
        if dob >= datetime.date.today():
            raise forms.ValidationError("The date cannot be the future.")
        if (datetime.date.today() - dob).days/365 < 18:
            raise forms.ValidationError("You must be over 18 to be a customer.")
        return dob
 
'''
This class is used to create a form to edit existing User information.
'''           
class EditUserProfileForm(forms.ModelForm):
    email = forms.EmailField(max_length=60, label = "Email", widget = forms.EmailInput)
    dob = forms.DateField(label = "Date of birth", widget=forms.DateInput(format=('%Y-%m-%d'), 
                                                        attrs={'class': 'form-control', 'placeholder': 'Select a date',
                                                        'type': 'date'}))
    bio = forms.CharField(max_length=250, widget=forms.Textarea)
    avatar = forms.ImageField(widget=forms.FileInput)
    
    '''
    The constructor will configure certain fields before generating form fields.
    '''
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['avatar'].required = False
        self.fields['bio'].required = False
        
    class Meta:
        model = User
        fields = ("email", "first_name", "last_name", "dob", "avatar", "bio")
      
    '''
    This function is used to validate the date of birth value
    from the form. It will throw a ValidationError if it is invalid.
    ---
    Returns
        dob
    '''
    def clean_dob(self):
        dob = self.cleaned_data.get("dob")
        if dob >= datetime.date.today():
            raise forms.ValidationError("The date cannot be the future.")
        if (datetime.date.today() - dob).days/365 < 18:
            raise forms.ValidationError("You must be over 18 to be a customer.")
        return dob
            
    '''
    This function is will change existing user field values with values
    from the form. It will save this change in the database.
    ---
    Returns
        user
    '''
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get("email")
        user.first_name = self.cleaned_data.get("first_name")
        user.last_name = self.cleaned_data.get("last_name")
        user.dob = self.cleaned_data.get("dob")
        user.avatar = self.cleaned_data.get("avatar")
        user.bio = self.cleaned_data.get("bio")
        
        if commit:
            user.save()
        return user

user/views.py
# Create your views here.
from django.shortcuts import render, redirect
from .forms import RegisterForm, EditUserProfileForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms  import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

'''
This module defines the views for user app.
'''
'''
This is the register view. It will generate a 
registration form and creates a new user with the form.
'''
def register(request):
    if request.user.is_authenticated:
        return redirect("user:profile")
    
    context = {}
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Account {} has been created. You may now login!"
                             .format(form.cleaned_data.get("username")))
            return redirect("user:login")
        else:
            context = {'form': form} #Form with request.Post
    else:
        context = {'form': form} #Form without request.Post
    return render(request, 'user/register.html', context)

'''
This is the profile view. The user must be logged in for it
to be accessible. It will display the user's information.
'''
class ProfileView(LoginRequiredMixin, generic.DetailView):
    login_url = "/login/"
    template_name =  "user/profile.html"
    
    #Set the object for this view as the current user
    def get_object(self):
        user = self.request.user
        return user
    
    def get_context_data(self, **kwargs):
        context = super(ProfileView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["base_template_name"] = "base_superuser.html"
        else:
            context["base_template_name"] = "base_user.html"     
        return context

'''
This is the edit profile view. It will allow the user to
modify their account's information, except username and password.
The user must be logged in to access this view.
'''
class EditProfileView(LoginRequiredMixin, generic.UpdateView):
    form_class = EditUserProfileForm
    template_name = "user/edit.html"
    success_url = "/profile/"
    
    #Set the object for this view as the current user
    def get_object(self):
        return self.request.user
    
    def get_context_data(self, **kwargs):
        context = super(EditProfileView, self).get_context_data(**kwargs)
        if self.request.user.is_superuser:
            context["base_template_name"] = "base_superuser.html"
        else:
            context["base_template_name"] = "base_user.html"     
        return context

'''
This is the change password view. It will allow the user to change their
password.
'''
@login_required(login_url="user:login")
def change(request):
    context = {}
    form = PasswordChangeForm(user=request.user)
    if request.method == "POST":
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "You have successfully changed your password.")
            return redirect("user:profile")
        else:
            messages.error(request, "Please correct the error.")
            
    context["form"] = form        
    if request.user.is_superuser:
        context["base_template_name"] = "base_superuser.html"
    else:
        context["base_template_name"] = "base_user.html"     
    
            
    return render(request, "user/change.html", context)

user/templates/user/change.html
{% extends base_template_name %}
{% load static %}

{% block title %}Edit Profile{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'user/css/edit_style.css' %}">
{% endblock extra_head %}

{% block content %}
<h1>Change Password</h1>
<form method="POST" action="">
    {% csrf_token %}
    {% for field in form %}
        <p>  
                {{field.label}}
                {{field}}
                
                {%if field.help_text %}
                    <small style="color: black;">{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p style="color: darkred;">{{error}}</p>
                {% endfor %}
        </p>
         {% endfor %}
    <Button type='submit'>Submit</Button>
</form>

{% endblock content %}

user/templates/user/edit.html
{% extends base_template_name %}
{% load static %}

{% block title %}Edit Profile{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'user/css/edit_style.css' %}">
{% endblock extra_head %}

{% block content %}
<h1>Edit Profile</h1>
<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
        {% for field in form %}
        <p>  
            {{field.label}}
            {{field}}
                
            {%if field.help_text %}
                <small style="color: grey;">{{field.help_text}}</small>
            {% endif %}
            {% for error in field.errors %}
                  <p style="color: red;">{{error}}</p>
            {% endfor %}
        </p>
         {% endfor %}
    <button type="Submit">Update</button>
</form>

{% endblock content %}

user/templates/user/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}Login{% endblock title %}

{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'user/css/login_style.css' %}">
{% endblock extra_head %}

{% block content %}
    <h1>Login</h1>
    <section>
    <form method="POST" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <Button type='submit'>Login</button>
        <p class='not_as_p' id='no_acc'><a href="{% url 'user:register' %}">Don't have an account?</a></p>
    </form>
</section>

    {% for message in messages %}
        <p class='not_as_p'>{{message}}</p>
    {% endfor %}
{% endblock content %}

user/templates/user/profile.html
{% extends base_template_name %}
{% load static %}

{% block title %}Profile{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'user/css/profile_style.css' %}">
{% endblock extra_head %}

{% block content %}
<section id="links">
    <p><a href="{% url 'user:edit' %}">Edit Profile</a></p>
    <p><a href="{% url 'user:change' %}">Change password</a></p>
    <p><a href="{% url 'item:user_listings' %}">Listings</a></p>
    <p><a href="{% url 'item:user_sold' %}">Sold Items</a></p>
    <p><a href="{% url 'order:user_orders' %}">Orders</a></p>
</section>

 <section id='profile'>
     <h1>Profile</h1>
     <div id='user'>
         {% if user.avatar %}
            <img src="{% static user.avatar.url %}" alt="none2" width=300 height=300>
        {% else %}
            <img src="{% static 'user/image/default-avatar.png' %}" alt="none" width=300 height=300>
        {% endif %}
        <div id='info'>
            <p>Username: <span>{{user.username}}</span></p>
            <p>Balance: <span id='balance'>${{user.balance}}</span></p>
            <p>First name: <span>{{user.first_name}}</span></p>
            <p>Last name: <span>{{user.last_name}}</span></p>
            <p>Email: <span>{{user.email}}</span></p>   
            <p>Date of birth: <span>{{user.dob}}</span></p>
        </div>
    </div>
    <textarea id='bio' readonly>Bio: 
    {{user.bio}}
    </textarea>
</section>


{% endblock content %}

user/templates/user/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock title %}
{% block extra_head %} 
    <link rel="stylesheet" href="{% static 'user/css/register_style.css' %}">
{% endblock extra_head %}

{% block content %}

<h1>Register</h1> 
<form method="POST" action="">
    {% csrf_token %}
    {% for field in form %}
        <p>  
            {{field.label}}
            {{field}}
                

            
            {% for error in field.errors %}
                <p style="color: darkred;">{{error}}</p>
            {% endfor %}
        </p>
         {% endfor %}
         
        <Button type='submit'>Register</Button>
</form>
<p id='acc_already'><a href="{% url 'user:login' %}">Already have an account? </a></p>

{% endblock content %}