item/urls.py
# -*- coding: utf-8 -*-
"""
Created on Fri Apr 23 21:10:14 2021

@author: Vashti
"""

from . import views
from django.urls import path

app_name = 'item'

urlpatterns = [
    path("item/<int:pk>/", views.ItemView.as_view(), name="view"),
    path("item/create/", views.ItemCreateView.as_view(), name="create"),
    path("item/<int:pk>/edit/", views.ItemEditView.as_view(), name='edit'),
    path("item/<int:pk>/delete/", views.ItemDeleteView.as_view(), name='delete'),
    path("profile/listings", views.UserItemsView.as_view(), name='user_listings'),
    path("profile/sold", views.UserSoldView.as_view(), name='user_sold'),
    ]

kijiji_like/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls', namespace="user")),
    path('', include('item.urls', namespace="item")),
    path('', include('like.urls', namespace="like")),
    path('', include('comment.urls', namespace="comment")),
    path('', include('order.urls', namespace="order")),
    path('', include('search.urls', namespace='search')),
]

search/urls.py
from . import views
from django.urls import path

app_name = 'search'

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("search/", views.SearchView.as_view(), name="search"),
    ]

user/urls.py
# -*- coding: utf-8 -*-
"""
This module contains the urls of the user app.
Created on Thu Apr 22 10:58:47 2021

@author: Vashti
"""
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'user'

urlpatterns = [
    path("register/", views.register, name='register'),
    path("login/", auth_views.LoginView.as_view(template_name="user/login.html"), name='login'),
    path("profile/", views.ProfileView.as_view(), name='profile'),
    path("logout/", auth_views.LogoutView.as_view(), name='logout'),
    path("profile/edit/", views.EditProfileView.as_view(), name='edit'),
    path("profile/change/", views.change, name='change')
    ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="{% static 'base/base_style.css' %}">
    <title>Kujuju - {% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="style.css">
    {% block extra_head %} {% endblock extra_head %}
</head>

<body>
    <div id="menu">
        <div id="title">
            <h1><a href="{% url 'search:index' %}">Kujuju</a></h1>
        </div>
        <div id="options">
        {% block options %}
            <ul>
                <li><a href="{% url 'user:login' %}">Login</a></li>
                <li><a href="{% url 'user:register' %}">Register</a></li>
            </ul>
        {% endblock options %}
        </div>
    </div>
    <div id="content">
    {% block content %}
    {% endblock %}
    </div>
    <footer>
        <p>Django project made by Vashti Lanz Rubio.</p>
    </footer>
    
</body>
</html>

templates/base_superuser.html
{% extends "base.html" %}
{% block options %}
<ul>
     <li id="post_option"><a href="{% url 'item:create' %}">Post New Item</a></li>
    <li><a href="/admin">Admin Page</a></li>
    <li><a href="{% url 'user:profile' %}">My Profile</a></li>
    <li><a href="{% url 'user:logout' %}">Logout</a></li>
 </ul>
{% endblock options %}

templates/base_user.html
{% extends "base.html" %}
{% block options %}
<ul>
     <li id="post_option"><a href="{% url 'item:create' %}">Post New Item</a></li>
    <li><a href="{% url 'user:profile' %}">My Profile</a></li>
    <li><a href="{% url 'user:logout' %}">Logout</a></li>
 </ul>
{% endblock options %}